newsaggr/newsaggr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls'))
]

newsaggr/user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views
from django.urls.base import reverse_lazy

app_name = 'users'
urlpatterns = [
    path('',views.index,name="index"),
    path('business/',views.business,name="business"),
    path('entertainment/',views.entertainment,name="entertainment"),
    path('science/',views.science,name="science"),
    path('health',views.health,name="health"),
    path('sports/',views.sports,name="sports"),
    path('technology/',views.technology,name="technology"),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',views.loggout, name='logout'),
    path('signup/',views.signup,name="signup"),
    path('forgot/',views.forgetpass,name="forgot"),
    path('preferance/',views.preferance,name="preferance"),
#    path('userprofile/',views.userprofile,name="userprofile"),'''
]

newsaggr/templates/business.html
<!DOCTYPE html>
{% load static %}
 <html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href={% static "css/main.css"%}>
        <!-- google fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Raleway:wght@300;400;500;700;900&display=swap" rel="stylesheet">
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/dbed6b6114.js" crossorigin="anonymous"></script>
    </head>
    <body>

        <!-- header -->
        <header>
            <div class = "navigation-container">
                <div class = "top-head">
                    <div class = "web-name">
                        <h1>NEWSBLOG</h1>
                    </div>

                    <div class = "ham-btn">
                        <span>
                            <i class = "fas fa-bars"></i>
                        </span>
                    </div>

                    <div class = "times-btn">
                        <span>
                            <i class = "fas fa-times"></i>
                        </span>
                    </div>
                </div>

                <!-- nav bar -->

                <div class = "nav-bar" id = "nav-bar">
                    <nav>
                        <ul>
                            <li><a href = {% url 'users:index' %}>HOME</a></li>
                            <li><a href = {% url 'users:business' %}>BUSINESS</a></li>
                            <li><a href = {% url 'users:entertainment' %}>ENTERTAINMENT</a></li>
                            <li><a href = {% url 'users:sports' %}>SPORTS</a></li>
                            <li><a href = {% url 'users:technology' %}>TECHNOLOGY</a></li>
                            <li><a href = {% url 'users:health' %}>HEALTH</a></li>
                            <li><a href = {% url 'users:science' %}>SCIENCE</a></li>
                            <li><a href="#"> <style></style></a></li>
                            {% if user.is_authenticated %}
                                <li style="color:aqua;"><h3>Welcome {{ user.username }}!</h3></li>
                                <li><a href="{% url 'users:logout' %}" style="color:aqua;">LOGOUT</a></li>
                            {% else %}
                                <li><a href = {% url 'users:signup' %} style="color:aqua;">SIGN UP</a></li>
                                <li><a href = {% url 'users:login' %} style="color:aqua;">LOGIN</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <section class = "banner">
            <div class = "banner-main-content">
                <h2>GET THE WORLD'S LATEST News</h2>
                <h3>World's Leading News Portal</h3>
                <div class = "current-news-head">
                    {%for i,j,k in top%}
                    <a href={{k}} target="_blank">
                    <h3>{{i}}<span>{{j}}</span></h3>
                    </a>
                    {%endfor%}
                </div>
            </div>

            <div class = "banner-sub-content">
                {%for i,j,k,l,m in trendings%}
                    <div class = "hot-topic">
                        <img src = {{m}} alt = "">

                        <div class = "hot-topic-content">
                            <h2>{{i}}</h2>

                            <h3>{{j}}</h3>
                            <p>{{k}}</p>
                            <a href = {{l}} target="_blank">Read More</a>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </section>
        
        <hr>

        <main>
            <section class = "main-container-left">
                <h2>Top Stories</h2>
                {% for i,j,k,l in topstoriestop%}
                <div class = "container-top-left">
                    <article>
                        <img src = {{l}}>

                        <div>
                            <h3>{{i}}</h3>

                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More <span>>></span></a>
                        </div>
                    </article>
                </div>
                {%endfor%}
                <div class = "container-bottom-left">
                    {%for i,j,k,l in topstoriesbottom%}
                    <article>
                        <img src = {{l}}>
                        <div>
                            <h3>{{i}}</h3>
                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More<span>>></span></a>
                        </div>
                    </article>
                    {%endfor%}
                </div>
            </section>

            <section class = "main-container-right">
                <h2>Latest Stories</h2>
                {% for i,j,k,l in latest%}
                <article>
                    <h4>just in </h4>
                    <div>
                        <h2>{{i}}</h2>

                        <p>{{j}}</p>

                        <a href ={{k}} target="_blank">Read More <span>>></span></a>
                    </div>
                    <img src ={{l}}>
                </article>
                {%endfor%}
            </section>
        </main>

        <footer>
            <div class = "footer-container">
                <div class = "footer-left">
                    <h2>NEWSBLOG</h2>
                    <p>Here we provide a compiled list of best news,taglines,business mottos and sayings we could find</p>
                </div>
                <div class = "footer-right">
                    <h2>Contact Us.</h2>
                    <p>Email :: techphantom@gmail.com</p>
                </div>
            </div>
        </footer>


        <script src={% static "script.js"%} async defer></script>
    </body>
</html>

newsaggr/templates/entertainment.html
<!DOCTYPE html>
{% load static %}
 <html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href={% static "css/main.css"%}>
        <!-- google fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Raleway:wght@300;400;500;700;900&display=swap" rel="stylesheet">
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/dbed6b6114.js" crossorigin="anonymous"></script>
    </head>
    <body>

        <!-- header -->
        <header>
            <div class = "navigation-container">
                <div class = "top-head">
                    <div class = "web-name">
                        <h1>NEWSBLOG</h1>
                    </div>

                    <div class = "ham-btn">
                        <span>
                            <i class = "fas fa-bars"></i>
                        </span>
                    </div>

                    <div class = "times-btn">
                        <span>
                            <i class = "fas fa-times"></i>
                        </span>
                    </div>
                </div>

                <!-- nav bar -->

                <div class = "nav-bar" id = "nav-bar">
                    <nav>
                        <ul>
                            <li><a href = {% url 'users:index' %}>HOME</a></li>
                            <li><a href = {% url 'users:business' %}>BUSINESS</a></li>
                            <li><a href = {% url 'users:entertainment' %}>ENTERTAINMENT</a></li>
                            <li><a href = {% url 'users:sports' %}>SPORTS</a></li>
                            <li><a href = {% url 'users:technology' %}>TECHNOLOGY</a></li>
                            <li><a href = {% url 'users:health' %}>HEALTH</a></li>
                            <li><a href = {% url 'users:science' %}>SCIENCE</a></li>
                            <li><a href="#"> <style></style></a></li>
                            {% if user.is_authenticated %}
                                <li style="color:aqua;"><h3>Welcome {{ user.username }}!</h3></li>
                                <li><a href="{% url 'users:logout' %}" style="color:aqua;">LOGOUT</a></li>
                            {% else %}
                                <li><a href = {% url 'users:signup' %} style="color:aqua;">SIGN UP</a></li>
                                <li><a href = {% url 'users:login' %} style="color:aqua;">LOGIN</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <section class = "banner">
            <div class = "banner-main-content">
                <h2>GET THE WORLD'S LATEST News</h2>
                <h3>World's Leading News Portal</h3>
                <div class = "current-news-head">
                    {%for i,j,k in top%}
                    <a href={{k}} target="_blank">
                    <h3>{{i}}<span>{{j}}</span></h3>
                    </a>
                    {%endfor%}
                </div>
            </div>

            <div class = "banner-sub-content">
                {%for i,j,k,l,m in trendings%}
                    <div class = "hot-topic">
                        <img src = {{m}} alt = "">

                        <div class = "hot-topic-content">
                            <h2>{{i}}</h2>

                            <h3>{{j}}</h3>
                            <p>{{k}}</p>
                            <a href = {{l}} target="_blank">Read More</a>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </section>
        
        <hr>

        <main>
            <section class = "main-container-left">
                <h2>Top Stories</h2>
                {% for i,j,k,l in topstoriestop%}
                <div class = "container-top-left">
                    <article>
                        <img src = {{l}}>

                        <div>
                            <h3>{{i}}</h3>

                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More <span>>></span></a>
                        </div>
                    </article>
                </div>
                {%endfor%}
                <div class = "container-bottom-left">
                    {%for i,j,k,l in topstoriesbottom%}
                    <article>
                        <img src = {{l}}>
                        <div>
                            <h3>{{i}}</h3>
                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More<span>>></span></a>
                        </div>
                    </article>
                    {%endfor%}
                </div>
            </section>

            <section class = "main-container-right">
                <h2>Latest Stories</h2>
                {% for i,j,k,l in latest%}
                <article>
                    <h4>just in </h4>
                    <div>
                        <h2>{{i}}</h2>

                        <p>{{j}}</p>

                        <a href ={{k}} target="_blank">Read More <span>>></span></a>
                    </div>
                    <img src ={{l}}>
                </article>
                {%endfor%}
            </section>
        </main>

        <footer>
            <div class = "footer-container">
                <div class = "footer-left">
                    <h2>NEWSBLOG</h2>
                    <p>Here we provide a compiled list of best news,taglines,business mottos and sayings we could find</p>
                </div>
                <div class = "footer-right">
                    <h2>Contact Us.</h2>
                    <p>Email :: techphantom@gmail.com</p>
                </div>
            </div>
        </footer>


        <script src={% static "script.js"%} async defer></script>
    </body>
</html>

newsaggr/templates/forgot.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Forgot Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href={% static "css/util.css"%}>
	<link rel="stylesheet" type="text/css" href={% static "css/main2.css"%}>
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-color: black;">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						Can't Remember Your Password?
					</span>
					<div class="wrap-input100 validate-input m-b-23" data-validate = "email is reauired">
						<span class="label-input100">Your Email</span>
						<input class="input100" type="email" name="email" placeholder="Type your email">
					</div>
					{% if otp %}
					<div class="wrap-input100 validate-input m-b-23" data-validate = "Password is reauired">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="password" placeholder="Type your Password">
					</div>
					<div class="wrap-input100 validate-input m-b-23" data-validate = "Password is reauired">
						<span class="label-input100">Confirm Password</span>
						<input class="input100" type="password" name="password2" placeholder="Confirm your Password">
					</div>
					<div class="wrap-input100 validate-input m-b-23" data-validate = "Otp is reauired">
						<span class="label-input100">Otp</span>
						<input class="input100" type="text" name="otp1" placeholder="Type your otp">
					</div>
					{% endif %}
					
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type='submit'>
								Submit
							</button>
						</div>
					</div>
                    
					


					<div class="flex-col-c p-t-50">
						<span class="txt1 p-b-17">
							
						</span>

						<a href={%url 'users:login'%} class="txt2">
							Back to Log in
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
	<script src={% static "js/main.js"%}></script>

</body>
</html>

newsaggr/templates/health.html
<!DOCTYPE html>
{% load static %}
 <html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href={% static "css/main.css"%}>
        <!-- google fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Raleway:wght@300;400;500;700;900&display=swap" rel="stylesheet">
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/dbed6b6114.js" crossorigin="anonymous"></script>
    </head>
    <body>

        <!-- header -->
        <header>
            <div class = "navigation-container">
                <div class = "top-head">
                    <div class = "web-name">
                        <h1>NEWSBLOG</h1>
                    </div>

                    <div class = "ham-btn">
                        <span>
                            <i class = "fas fa-bars"></i>
                        </span>
                    </div>

                    <div class = "times-btn">
                        <span>
                            <i class = "fas fa-times"></i>
                        </span>
                    </div>
                </div>

                <!-- nav bar -->

                <div class = "nav-bar" id = "nav-bar">
                    <nav>
                        <ul>
                            <li><a href = {% url 'users:index' %}>HOME</a></li>
                            <li><a href = {% url 'users:business' %}>BUSINESS</a></li>
                            <li><a href = {% url 'users:entertainment' %}>ENTERTAINMENT</a></li>
                            <li><a href = {% url 'users:sports' %}>SPORTS</a></li>
                            <li><a href = {% url 'users:technology' %}>TECHNOLOGY</a></li>
                            <li><a href = {% url 'users:health' %}>HEALTH</a></li>
                            <li><a href = {% url 'users:science' %}>SCIENCE</a></li>
                            <li><a href="#"> <style></style></a></li>
                            {% if user.is_authenticated %}
                                <li style="color:aqua;"><h3>Welcome {{ user.username }}!</h3></li>
                                <li><a href="{% url 'users:logout' %}" style="color:aqua;">LOGOUT</a></li>
                            {% else %}
                                <li><a href = {% url 'users:signup' %} style="color:aqua;">SIGN UP</a></li>
                                <li><a href = {% url 'users:login' %} style="color:aqua;">LOGIN</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <section class = "banner">
            <div class = "banner-main-content">
                <h2>GET THE WORLD'S LATEST News</h2>
                <h3>World's Leading News Portal</h3>
                <div class = "current-news-head">
                    {%for i,j,k in top%}
                    <a href={{k}} target="_blank">
                    <h3>{{i}}<span>{{j}}</span></h3>
                    </a>
                    {%endfor%}
                </div>
            </div>

            <div class = "banner-sub-content">
                {%for i,j,k,l,m in trendings%}
                    <div class = "hot-topic">
                        <img src = {{m}} alt = "">

                        <div class = "hot-topic-content">
                            <h2>{{i}}</h2>

                            <h3>{{j}}</h3>
                            <p>{{k}}</p>
                            <a href = {{l}} target="_blank">Read More</a>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </section>
        
        <hr>

        <main>
            <section class = "main-container-left">
                <h2>Top Stories</h2>
                {% for i,j,k,l in topstoriestop%}
                <div class = "container-top-left">
                    <article>
                        <img src = {{l}}>

                        <div>
                            <h3>{{i}}</h3>

                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More <span>>></span></a>
                        </div>
                    </article>
                </div>
                {%endfor%}
                <div class = "container-bottom-left">
                    {%for i,j,k,l in topstoriesbottom%}
                    <article>
                        <img src = {{l}}>
                        <div>
                            <h3>{{i}}</h3>
                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More<span>>></span></a>
                        </div>
                    </article>
                    {%endfor%}
                </div>
            </section>

            <section class = "main-container-right">
                <h2>Latest Stories</h2>
                {% for i,j,k,l in latest%}
                <article>
                    <h4>just in </h4>
                    <div>
                        <h2>{{i}}</h2>

                        <p>{{j}}</p>

                        <a href ={{k}} target="_blank">Read More <span>>></span></a>
                    </div>
                    <img src ={{l}}>
                </article>
                {%endfor%}
            </section>
        </main>

        <footer>
            <div class = "footer-container">
                <div class = "footer-left">
                    <h2>NEWSBLOG</h2>
                    <p>Here we provide a compiled list of best news,taglines,business mottos and sayings we could find</p>
                </div>
                <div class = "footer-right">
                    <h2>Contact Us.</h2>
                    <p>Email :: techphantom@gmail.com</p>
                </div>
            </div>
        </footer>


        <script src={% static "script.js"%} async defer></script>
    </body>
</html>

newsaggr/templates/index.html
<!DOCTYPE html>
{% load static %}
 <html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href={% static "css/main.css"%}>
        <!-- google fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Raleway:wght@300;400;500;700;900&display=swap" rel="stylesheet">
        <!-- fontawesome -->
        <script src="https://kit.fontawesome.com/dbed6b6114.js" crossorigin="anonymous"></script>
    </head>
    <body>

        <!-- header -->
        <header>
            <div class = "navigation-container">
                <div class = "top-head">
                    <div class = "web-name">
                        <h1>NEWSBLOG</h1>
                    </div>

                    <div class = "ham-btn">
                        <span>
                            <i class = "fas fa-bars"></i>
                        </span>
                    </div>

                    <div class = "times-btn">
                        <span>
                            <i class = "fas fa-times"></i>
                        </span>
                    </div>
                </div>

                <!-- nav bar -->

                <div class = "nav-bar" id = "nav-bar">
                    <nav>
                        <ul>
                            <li><a href = {% url 'users:index' %}>HOME</a></li>
                            <li><a href = {% url 'users:business' %}>BUSINESS</a></li>
                            <li><a href = {% url 'users:entertainment' %}>ENTERTAINMENT</a></li>
                            <li><a href = {% url 'users:sports' %}>SPORTS</a></li>
                            <li><a href = {% url 'users:technology' %}>TECHNOLOGY</a></li>
                            <li><a href = {% url 'users:health' %}>HEALTH</a></li>
                            <li><a href = {% url 'users:science' %}>SCIENCE</a></li>
                            <li><a href="#"> <style></style></a></li>
                            {% if user.is_authenticated %}
                            <li style="color:aqua;"><h3>Welcome {{ user.username }}!</h3></li>
                            <li><a href="{% url 'users:logout' %}" style="color:aqua;">LOGOUT</a></li>
                            <li><a href="{% url 'users:preferance' %}" style="color:aqua;">Preferance</a></li>
                            {% else %}
                                <li><a href = {% url 'users:signup' %} style="color:aqua;">SIGN UP</a></li>
                                <li><a href = {% url 'users:login' %} style="color:aqua;">LOGIN</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        {% if user.is_authenticated %}
        {% for c,a,b in top%}
        <section class = "banner">
            <div class = "banner-main-content">
                <h2>{{c}}</h>
                <div class = "current-news-head">
                    {%for i,j,k in a %}
                    <a href={{k}} target="_blank">
                    <h3>{{i}}<span>{{j}}</span></h3>
                    </a>
                    {%endfor%}
                </div>
            </div>
            <div class = "banner-sub-content">
                {%for i,j,k,l,m in b%}
                    <div class = "hot-topic">
                        <img src = {{m}} alt = "">

                        <div class = "hot-topic-content">
                            <h2>{{i}}</h2>

                            <h3>{{j}}</h3>
                            <p>{{k}}</p>
                            <a href = {{l}} target="_blank">Read More</a>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </section>
        {%endfor%}
        {% else %}
        <section class = "banner">
            <div class = "banner-main-content">
                <h2>GET THE WORLD'S LATEST NEWSBLOG</h2>
                <h3>World's Leading NEWSBLOG Portal</h3>
                <div class = "current-news-head">
                    {%for i,j,k in top%}
                    <a href={{k}} target="_blank">
                    <h3>{{i}}<span>{{j}}</span></h3>
                    </a>
                    {%endfor%}
                </div>
            </div>

            <div class = "banner-sub-content">
                {%for i,j,k,l,m in trendings%}
                    <div class = "hot-topic">
                        <img src = {{m}} alt = "">

                        <div class = "hot-topic-content">
                            <h2>{{i}}</h2>

                            <h3>{{j}}</h3>
                            <p>{{k}}</p>
                            <a href = {{l}} target="_blank">Read More</a>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </section>
        
        <hr>

        <main>
            <section class = "main-container-left">
                <h2>Top Stories</h2>
                {% for i,j,k,l in topstoriestop%}
                <div class = "container-top-left">
                    <article>
                        <img src = {{l}}>

                        <div>
                            <h3>{{i}}</h3>

                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More <span>>></span></a>
                        </div>
                    </article>
                </div>
                {%endfor%}
                <div class = "container-bottom-left">
                    {%for i,j,k,l in topstoriesbottom%}
                    <article>
                        <img src = {{l}}>
                        <div>
                            <h3>{{i}}</h3>
                            <p>{{j}}</p>

                            <a href ={{k}} target="_blank">Read More<span>>></span></a>
                        </div>
                    </article>
                    {%endfor%}
                </div>
            </section>

            <section class = "main-container-right">
                <h2>Latest Stories</h2>
                {% for i,j,k,l in latest%}
                <article>
                    <h4>just in </h4>
                    <div>
                        <h2>{{i}}</h2>

                        <p>{{j}}</p>

                        <a href ={{k}} target="_blank">Read More <span>>></span></a>
                    </div>
                    <img src ={{l}}>
                </article>
                {%endfor%}
            </section>
        </main>
        {%endif%}
        <footer>
            <div class = "footer-container">
                <div class = "footer-left">
                    <h2>NEWSBLOG</h2>
                    <p>Here we provide a compiled list of best news,taglines,business mottos and sayings we could find</p>
                </div>
                <div class = "footer-right">
                    <h2>Contact Us.</h2>
                    <p>Email :: techphantom@gmail.com</p>
                </div>
            </div>
        </footer>

        <script src={% static "script.js"%} async defer></script>
    </body>
</html>

newsaggr/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href={% static "css/util.css"%}>
	<link rel="stylesheet" type="text/css" href={% static "css/main2.css"%}>

</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-color: black;">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form action={% url "users:login" %} class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						Log in
					</span>
					{% for field in form %}
					<div class="wrap-input100 validate-input m-b-23">
						<p class="label-input100">{{ field.label}}<br>{{ field }}
						</p>
					</div>
					{% endfor %}
					<div class="text-right p-t-8 p-b-31">
						<a href={% url 'users:forgot'%}>
							Forgot password?
						</a>
					</div>
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" method="POST">
								Log in
							</button>
						</div>
					</div>

					
					<div class="flex-col-c p-t-50">
						<span class="txt1 p-b-17">
							
						</span>

						<a href={%url 'users:signup'%} class="txt2">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
	<script src={% static "js/main.js"%}></script>

</body>
</html>

newsaggr/templates/logout.html
<div class="alert alert-success" role="alert">
    <h2 style="text-align: center;">Logged out!</h2>
</div>

<h3>Login again?</h3>
<a href="{% url 'users:login' %}">Login</a> <br>
<a href="{% url 'users:index' %}"> Or go back to home.</a>